targets:
  $default:
    builders:
      image_path_helper|image_builder:
        enabled: true

builders:
  image_builder:
    import: 'package:image_path_helper/builder.dart'
    builder_factories: ['imagePathBuilder']
    build_extensions: { '.dart': ['.g.dart'] }
    auto_apply: root_package
    build_to: source
    applies_builders: ["source_gen|combining_builder"]